### ISSUE TITLE
If a Place is deleted in Adventist Cloud, the Site should archive automatically also.

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#180]

**Comment by danlewis** [comment]
If a place is archived in Adventist Cloud, the site's status will change to disabled.
This will appear on the daily slack notification message so that an admin can decide if the site should be deleted. This might not always be the case - e.g. if two churches merge, it doesn't mean I want to delete the site, but simply change the place UUID
