### ISSUE TITLE
Cloudflare:  Error 1014: CNAME Cross-User Banned

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#210]
When user tried using their cloudflare to our cloudflare they got:
Error 1014: CNAME Cross-User Banned

Do we need a 'pro' account as hinted at the end of this support note:

> A CNAME Cross-User Banned error is due to Cloudflare's prohibition on CNAME records pointing from one Cloudflare user into another Cloudflare user's account.
> 
> Cloudflare blocks these cross-user CNAME records to ensure the security of Cloudflare customers.  Cloudflare applies security and performance filtering to incoming traffic at our globally distributed edge based on individually configured zone settings, and uses the incoming host to determine which settings to apply.
> 
> CNAME records are permitted within a domain (e.g. www.example.com CNAME bigserver.example.com), and across zones within a user account (e.g. www.example.com CNAME www.example.net).
> 
> Incoming CNAME records from other user accounts can be permitted for Pro, Business, and Enterprise customers by contacting support.

**Comment by danlewis** [comment]
This has been resolved. I've setup a working example with helloworld.adspace.org.au

Fix: Cloudflare will now allow other users to point to dns.adventist.place

Very Important: Crypto must be set to "Full SSL" otherwise the user will see the 526 error. Note that this will not work for "Full SSL (strict)"
